In [1]:
import xgboost as xgb

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

## XGBoost Training

In [4]:
bert_label = pd.read_csv('train_data_bert_label.csv', header = 0)[['predicted_label']]
bert_label

        predicted_label
0                     1
1                     1
2                     1
3                     1
4                     1
...                 ...
416763                0
416764                0
416765                0
416766                0
416767                0

[416768 rows x 1 columns]

In [5]:
train = pd.read_csv('train_data_with_feature_ver_3.csv')
train = train.join(bert_label)
train

,Unnamed: 0,original_text,label,processed_text,text_length,average_AoA_Kup_lem,percentage_of_basic_words,average_concreteness,average_percentage_known,predicted_label
0,0,There is manuscript evidence that Austen conti...,1,"['there', 'is', 'manuscript', 'evidence', 'tha...",4,5.923793,0.552632,2.354815,0.995926,1
1,1,"In a remarkable comparative analysis , Mandaea...",1,"['in', 'a', 'remarkable', 'comparative', 'anal...",2,7.499286,0.285714,2.117500,0.994167,1
2,2,"Before Persephone was released to Hermes , who...",1,"['before', 'persephone', 'was', 'released', 't...",4,5.322162,0.619048,2.357647,0.992647,1
3,3,Cogeneration plants are commonly found in dist...,1,"['cogeneration', 'plants', 'are', 'commonly', ...",3,6.738889,0.312500,2.997143,0.993333,1
4,4,"Geneva -LRB- , ; , ; , ; ; -RRB- is the second...",1,"['geneva', 'lrb', '', '', '', '', '', '', '', ...",3,5.396667,0.500000,2.364667,0.989333,1
...,...,...,...,...,...,...,...,...,...,...
416763,416763,A Duke Nukem 3D version has been sold for Xbox...,0,"['a', 'duke', 'nukem', '3d', 'version', 'has',...",1,5.790000,0.533333,2.732000,0.982000,0
416764,416764,"However , it is becoming replaced as a method ...",0,"['however', '', 'it', 'is', 'becoming', 'repla...",1,6.581875,0.666667,2.158571,0.992143,0
416765,416765,There are hand gestures in both Hindu and Budd...,0,"['there', 'are', 'hand', 'gestures', 'in', 'bo...",1,6.788889,0.600000,2.973750,1.000000,0
416766,416766,"If it is necessary to use colors , try to choo...",0,"['if', 'it', 'is', 'necessary', 'to', 'use', '...",4,4.932222,0.666667,2.504167,0.995833,0
416767,416767,"Calgary Stampeders ,",0,"['calgary', 'stampeders', '']",0,0.000000,0.000000,NaN,1.000000,0

In [6]:
train = pd.read_csv('train_data_with_feature_ver_3.csv', index_col = 0)
train

,original_text,label,processed_text,text_length,average_AoA_Kup_lem,percentage_of_basic_words,average_concreteness,average_percentage_known
0,There is manuscript evidence that Austen conti...,1,"['there', 'is', 'manuscript', 'evidence', 'tha...",4,5.923793,0.552632,2.354815,0.995926
1,"In a remarkable comparative analysis , Mandaea...",1,"['in', 'a', 'remarkable', 'comparative', 'anal...",2,7.499286,0.285714,2.117500,0.994167
2,"Before Persephone was released to Hermes , who...",1,"['before', 'persephone', 'was', 'released', 't...",4,5.322162,0.619048,2.357647,0.992647
3,Cogeneration plants are commonly found in dist...,1,"['cogeneration', 'plants', 'are', 'commonly', ...",3,6.738889,0.312500,2.997143,0.993333
4,"Geneva -LRB- , ; , ; , ; ; -RRB- is the second...",1,"['geneva', 'lrb', '', '', '', '', '', '', '', ...",3,5.396667,0.500000,2.364667,0.989333
...,...,...,...,...,...,...,...,...
416763,A Duke Nukem 3D version has been sold for Xbox...,0,"['a', 'duke', 'nukem', '3d', 'version', 'has',...",1,5.790000,0.533333,2.732000,0.982000
416764,"However , it is becoming replaced as a method ...",0,"['however', '', 'it', 'is', 'becoming', 'repla...",1,6.581875,0.666667,2.158571,0.992143
416765,There are hand gestures in both Hindu and Budd...,0,"['there', 'are', 'hand', 'gestures', 'in', 'bo...",1,6.788889,0.600000,2.973750,1.000000
416766,"If it is necessary to use colors , try to choo...",0,"['if', 'it', 'is', 'necessary', 'to', 'use', '...",4,4.932222,0.666667,2.504167,0.995833
416767,"Calgary Stampeders ,",0,"['calgary', 'stampeders', '']",0,0.000000,0.000000,NaN,1.000000

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 416768 entries, 0 to 416767
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   original_text              416768 non-null  object
 1   label                      416768 non-null  int64
 2   processed_text             416768 non-null  object
 3   text_length                416768 non-null  int64
 4   average_AoA_Kup_lem        416760 non-null  float64
 5   percentage_of_basic_words  416768 non-null  float64
 6   average_concreteness       404958 non-null  float64
 7   average_percentage_known   416768 non-null  float64
dtypes: float64(4), int64(2), object(2)
memory usage: 28.6+ MB

In [23]:
X, y = train[['average_AoA_Kup_lem',
       'percentage_of_basic_words', 'average_concreteness',
       'average_percentage_known', 'text_length']], train['label']

In [8]:
import matplotlib.pyplot as plt

In [22]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

In [ ]:
>>> from sklearn.model_selection import cross_val_score
>>> clf = svm.SVC(kernel='linear', C=1, random_state=42)
>>> scores = cross_val_score(clf, X, y, cv=5)
>>> scores
array([0.96..., 1. , 0.96..., 0.96..., 1. ])

In [10]:
from sklearn.model_selection import StratifiedShuffleSplit
sss= StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in sss.split(train, train['label']):
    strat_train_set = train.iloc[train_index]
    strat_test_set = train.iloc[test_index]
strat_train_set['label'].value_counts()/len(strat_train_set)

0    0.5
1    0.5
Name: label, dtype: float64

In [11]:
X_train, y_train = strat_train_set[['average_AoA_Kup_lem',
       'percentage_of_basic_words', 'average_concreteness',
       'average_percentage_known', 'text_length']], strat_train_set['label']

In [12]:
X_train.shape

(333414, 5)

In [13]:
y_train.shape

(333414,)

In [14]:
X_test, y_test = strat_test_set[['average_AoA_Kup_lem',
       'percentage_of_basic_words', 'average_concreteness',
       'average_percentage_known', 'text_length']], strat_test_set['label']

In [15]:
X_test.shape

(83354, 5)

In [16]:
y_test.shape

(83354,)

In [17]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# pipe = Pipeline([('scaler', MinMaxScaler()), ('imputer', SimpleImputer(strategy='mean'))])
pipe = Pipeline([('imputer', SimpleImputer(strategy='mean'))])

In [27]:
X = pipe.fit_transform(X)

In [19]:
transformed_X_train = pipe.fit_transform(X_train)
transformed_X_test = pipe.transform(X_test)

In [20]:
transformed_X_train

array([[4.72416667, 0.80769231, 2.86208333, 0.99666667, 2.        ],
       [5.42888889, 0.63636364, 2.2275    , 1.        , 1.        ],
       [5.6       , 0.2       , 4.52      , 1.        , 0.        ],
       ...,
       [5.892     , 0.38888889, 2.296     , 0.993     , 1.        ],
       [4.989     , 0.76923077, 3.26909091, 0.99636364, 1.        ],
       [6.60428571, 0.40909091, 3.32357143, 0.99142857, 3.        ]])

In [21]:
transformed_X_test

array([[6.23344828, 0.58823529, 2.15777778, 0.9962963 , 3.        ],
       [4.53777778, 0.78571429, 2.45      , 0.99      , 1.        ],
       [6.14363636, 0.5       , 2.48818182, 0.99636364, 1.        ],
       ...,
       [5.57810811, 0.59090909, 2.59676471, 0.99235294, 4.        ],
       [4.96      , 0.6       , 1.69666667, 1.        , 0.        ],
       [5.82394737, 0.52941176, 2.23805556, 0.99277778, 4.        ]])

In [29]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=10)
scores = cross_val_score(neigh, X, y, cv=5)

In [31]:
neigh.fit(transformed_X_train, y_train)
y_pred = neigh.predict(transformed_X_test)

In [35]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import roc_auc_score

In [36]:
def result_evalation(predict_result, true_result):
    accuracy=accuracy_score(true_result, predict_result)
    print("accuracy:", accuracy)
    precision=precision_score(true_result, predict_result)
    print("precision:", precision)
    recall=recall_score(true_result, predict_result)
    print("recall:",recall )
    f1=f1_score(true_result, predict_result)
    print("f1:", f1)
    auc=roc_auc_score(true_result, predict_result)
    print("auc:", auc)
    return accuracy,precision,recall, f1, auc

In [38]:
result_evalation(y_pred, y_test)

accuracy: 0.6401852340619526
precision: 0.6544776711350837
recall: 0.5939247066727451
f1: 0.6227326473621978
auc: 0.6401852340619526

(0.6401852340619526,
 0.6544776711350837,
 0.5939247066727451,
 0.6227326473621978,
 0.6401852340619526)

In [276]:
dtrain = xgb.DMatrix(transformed_X_train, label = y_train)

In [277]:
dvalid = xgb.DMatrix(transformed_X_test, label = y_test)

In [337]:
from sklearn.linear_model import LogisticRegression

In [338]:
logistic_clf = LogisticRegression()
logistic_clf.fit(transformed_X_train, y_train)
logistic_clf.score(transformed_X_test, y_test)

0.6093048923866881

In [339]:
from sklearn.svm import SVC

In [ ]:
svc_clf = SVC()
svc_clf.fit(transformed_X_train, y_train)
svc_clf.score(transformed_X_test, y_test)

In [320]:
param_dist = {'objective':'binary:logistic', 'n_estimators':100, 'max_depth':15, 'eta': 0.8}
clf = xgb.XGBModel(**param_dist)

In [321]:
clf.fit(transformed_X_train, y_train,
        eval_set=[(transformed_X_train, y_train), (transformed_X_test, y_test)],
        eval_metric='error',
        verbose=True)

[0]	validation_0-error:0.30759	validation_1-error:0.35152
[1]	validation_0-error:0.28809	validation_1-error:0.34830
[2]	validation_0-error:0.27530	validation_1-error:0.34802
[3]	validation_0-error:0.26987	validation_1-error:0.34765
[4]	validation_0-error:0.26657	validation_1-error:0.34715
[5]	validation_0-error:0.26171	validation_1-error:0.34635
[6]	validation_0-error:0.25316	validation_1-error:0.34622
[7]	validation_0-error:0.24993	validation_1-error:0.34671
[8]	validation_0-error:0.24844	validation_1-error:0.34668
[9]	validation_0-error:0.24260	validation_1-error:0.34584
[10]	validation_0-error:0.23813	validation_1-error:0.34574
[11]	validation_0-error:0.23315	validation_1-error:0.34529
[12]	validation_0-error:0.22853	validation_1-error:0.34484
[13]	validation_0-error:0.22265	validation_1-error:0.34508
[14]	validation_0-error:0.21696	validation_1-error:0.34398
[15]	validation_0-error:0.21254	validation_1-error:0.34365
[16]	validation_0-error:0.20899	validation_1-error:0.34326
[17]	validation_0-error:0.20792	validation_1-error:0.34267
[18]	validation_0-error:0.20039	validation_1-error:0.34177
[19]	validation_0-error:0.19845	validation_1-error:0.34142
[20]	validation_0-error:0.19338	validation_1-error:0.34159
[21]	validation_0-error:0.19084	validation_1-error:0.34085
[22]	validation_0-error:0.18911	validation_1-error:0.34105
[23]	validation_0-error:0.18645	validation_1-error:0.34085
[24]	validation_0-error:0.18422	validation_1-error:0.34109
[25]	validation_0-error:0.18204	validation_1-error:0.34080
[26]	validation_0-error:0.17905	validation_1-error:0.34033
[27]	validation_0-error:0.17700	validation_1-error:0.34018
[28]	validation_0-error:0.17397	validation_1-error:0.33998
[29]	validation_0-error:0.17009	validation_1-error:0.33901
[30]	validation_0-error:0.16557	validation_1-error:0.33918
[31]	validation_0-error:0.16345	validation_1-error:0.33914
[32]	validation_0-error:0.16298	validation_1-error:0.33910
[33]	validation_0-error:0.16065	validation_1-error:0.33865
[34]	validation_0-error:0.15755	validation_1-error:0.33810
[35]	validation_0-error:0.15679	validation_1-error:0.33782
[36]	validation_0-error:0.15652	validation_1-error:0.33768
[37]	validation_0-error:0.15623	validation_1-error:0.33758
[38]	validation_0-error:0.15491	validation_1-error:0.33779
[39]	validation_0-error:0.15444	validation_1-error:0.33786
[40]	validation_0-error:0.15400	validation_1-error:0.33803
[41]	validation_0-error:0.15248	validation_1-error:0.33769
[42]	validation_0-error:0.15001	validation_1-error:0.33804
[43]	validation_0-error:0.14696	validation_1-error:0.33774
[44]	validation_0-error:0.14566	validation_1-error:0.33817
[45]	validation_0-error:0.14420	validation_1-error:0.33798
[46]	validation_0-error:0.13989	validation_1-error:0.33809
[47]	validation_0-error:0.13875	validation_1-error:0.33816
[48]	validation_0-error:0.13603	validation_1-error:0.33750
[49]	validation_0-error:0.13410	validation_1-error:0.33746
[50]	validation_0-error:0.13253	validation_1-error:0.33713
[51]	validation_0-error:0.13202	validation_1-error:0.33718
[52]	validation_0-error:0.13071	validation_1-error:0.33733
[53]	validation_0-error:0.12943	validation_1-error:0.33714
[54]	validation_0-error:0.12735	validation_1-error:0.33738
[55]	validation_0-error:0.12542	validation_1-error:0.33749
[56]	validation_0-error:0.12461	validation_1-error:0.33754
[57]	validation_0-error:0.12424	validation_1-error:0.33761
[58]	validation_0-error:0.12103	validation_1-error:0.33749
[59]	validation_0-error:0.11877	validation_1-error:0.33661
[60]	validation_0-error:0.11862	validation_1-error:0.33643
[61]	validation_0-error:0.11789	validation_1-error:0.33654
[62]	validation_0-error:0.11738	validation_1-error:0.33665
[63]	validation_0-error:0.11486	validation_1-error:0.33603
[64]	validation_0-error:0.11395	validation_1-error:0.33607
[65]	validation_0-error:0.11079	validation_1-error:0.33551
[66]	validation_0-error:0.10942	validation_1-error:0.33539
[67]	validation_0-error:0.10802	validation_1-error:0.33554
[68]	validation_0-error:0.10748	validation_1-error:0.33540
[69]	validation_0-error:0.10544	validation_1-error:0.33537
[70]	validation_0-error:0.10349	validation_1-error:0.33531
[71]	validation_0-error:0.10196	validation_1-error:0.33480
[72]	validation_0-error:0.10124	validation_1-error:0.33470
[73]	validation_0-error:0.09922	validation_1-error:0.33520
[74]	validation_0-error:0.09723	validation_1-error:0.33479
[75]	validation_0-error:0.09689	validation_1-error:0.33461
[76]	validation_0-error:0.09671	validation_1-error:0.33470
[77]	validation_0-error:0.09547	validation_1-error:0.33494
[78]	validation_0-error:0.09357	validation_1-error:0.33519
[79]	validation_0-error:0.09250	validation_1-error:0.33527
[80]	validation_0-error:0.09222	validation_1-error:0.33510
[81]	validation_0-error:0.09192	validation_1-error:0.33499
[82]	validation_0-error:0.09097	validation_1-error:0.33461
[83]	validation_0-error:0.09042	validation_1-error:0.33474
[84]	validation_0-error:0.08979	validation_1-error:0.33450
[85]	validation_0-error:0.08940	validation_1-error:0.33439
[86]	validation_0-error:0.08916	validation_1-error:0.33432
[87]	validation_0-error:0.08914	validation_1-error:0.33422
[88]	validation_0-error:0.08834	validation_1-error:0.33426
[89]	validation_0-error:0.08665	validation_1-error:0.33376
[90]	validation_0-error:0.08526	validation_1-error:0.33369
[91]	validation_0-error:0.08392	validation_1-error:0.33371
[92]	validation_0-error:0.08333	validation_1-error:0.33357
[93]	validation_0-error:0.08310	validation_1-error:0.33348
[94]	validation_0-error:0.08180	validation_1-error:0.33317
[95]	validation_0-error:0.08117	validation_1-error:0.33283
[96]	validation_0-error:0.08041	validation_1-error:0.33295
[97]	validation_0-error:0.08034	validation_1-error:0.33300
[98]	validation_0-error:0.07903	validation_1-error:0.33319
[99]	validation_0-error:0.07769	validation_1-error:0.33291

XGBModel(base_score=0.5, booster='gbtree', colsample_bylevel=1,
         colsample_bynode=1, colsample_bytree=1, eta=0.8, gamma=0, gpu_id=-1,
         interaction_constraints='', learning_rate=0.800000012,
         max_delta_step=0, max_depth=15, min_child_weight=1,
         monotone_constraints='()', n_jobs=8, num_parallel_tree=1,
         objective='binary:logistic', predictor='auto', random_state=0,
         reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
         tree_method='exact', validate_parameters=1)

## Prediction

In [231]:
test_bert_label = pd.read_csv('test_data_bert_label.csv', header = 0, index_col = 0)
test_bert_label.columns = ['predicted_label']
test_bert_label

        predicted_label
id
0                     0
1                     0
2                     0
3                     0
4                     1
...                 ...
119087                1
119088                1
119089                1
119090                1
119091                1

[119092 rows x 1 columns]

In [322]:
test = pd.read_csv('test_data_with_feature_ver_3.csv', index_col = 0)
test

,original_text,label,processed_text,text_length,average_AoA_Kup_lem,percentage_of_basic_words,average_concreteness,average_percentage_known
id,,,,,,,,
0,-2011,NaN,['2011'],0,0.00,0.0,NaN,1.00
1,-2011,NaN,['2011'],0,0.00,0.0,NaN,1.00
2,-2000,NaN,['2000'],0,0.00,0.0,NaN,1.00
3,-1997,NaN,['1997'],0,0.00,0.0,NaN,1.00
4,1.636,NaN,['1636'],0,0.00,0.0,NaN,1.00
...,...,...,...,...,...,...,...,...
119087,#NAME?,NaN,['name'],0,3.68,1.0,3.5,0.96
119088,#NAME?,NaN,['name'],0,3.68,1.0,3.5,0.96
119089,#NAME?,NaN,['name'],0,3.68,1.0,3.5,0.96
119090,#NAME?,NaN,['name'],0,3.68,1.0,3.5,0.96
119091,#NAME?,NaN,['name'],0,3.68,1.0,3.5,0.96

In [233]:
test = test.join(test_bert_label)
test

,original_text,label,processed_text,average_AoA_Kup_lem,percentage_of_basic_words,average_concreteness,average_percentage_known,predicted_label
id,,,,,,,,
0,-2011,NaN,['2011'],NaN,0.0,NaN,NaN,0
1,-2011,NaN,['2011'],NaN,0.0,NaN,NaN,0
2,-2000,NaN,['2000'],NaN,0.0,NaN,NaN,0
3,-1997,NaN,['1997'],NaN,0.0,NaN,NaN,0
4,1.636,NaN,['1636'],NaN,0.0,NaN,NaN,1
...,...,...,...,...,...,...,...,...
119087,#NAME?,NaN,['name'],3.68,1.0,3.5,0.96,1
119088,#NAME?,NaN,['name'],3.68,1.0,3.5,0.96,1
119089,#NAME?,NaN,['name'],3.68,1.0,3.5,0.96,1
119090,#NAME?,NaN,['name'],3.68,1.0,3.5,0.96,1
119091,#NAME?,NaN,['name'],3.68,1.0,3.5,0.96,1

In [323]:
X = test[['average_AoA_Kup_lem',
       'percentage_of_basic_words', 'average_concreteness',
       'average_percentage_known', 'text_length']]

In [324]:
X

,average_AoA_Kup_lem,percentage_of_basic_words,average_concreteness,average_percentage_known,text_length
id,,,,,
0,0.00,0.0,NaN,1.00,0
1,0.00,0.0,NaN,1.00,0
2,0.00,0.0,NaN,1.00,0
3,0.00,0.0,NaN,1.00,0
4,0.00,0.0,NaN,1.00,0
...,...,...,...,...,...
119087,3.68,1.0,3.5,0.96,0
119088,3.68,1.0,3.5,0.96,0
119089,3.68,1.0,3.5,0.96,0
119090,3.68,1.0,3.5,0.96,0
119091,3.68,1.0,3.5,0.96,0

In [325]:
transformed_X = pipe.transform(X)

In [326]:
transformed_X

array([[0.        , 0.        , 2.60366682, 1.        , 0.        ],
       [0.        , 0.        , 2.60366682, 1.        , 0.        ],
       [0.        , 0.        , 2.60366682, 1.        , 0.        ],
       ...,
       [3.68      , 1.        , 3.5       , 0.96      , 0.        ],
       [3.68      , 1.        , 3.5       , 0.96      , 0.        ],
       [3.68      , 1.        , 3.5       , 0.96      , 0.        ]])

In [327]:
ypred = clf.predict(transformed_X)

In [328]:
ypred

array([0.30558553, 0.30558553, 0.30558553, ..., 0.20303436, 0.20303436,
       0.20303436], dtype=float32)

In [329]:
result = ypred > 0.5

In [330]:
result = pd.DataFrame(result)

In [331]:
result[0] = result[0].astype(int)

In [332]:
result.columns = ['label']

In [333]:
result.index.name = 'id'

In [334]:
result.label.sum()

60978

In [335]:
result.to_csv('testing.csv')